name: simple_mashovapi
repository: https://github.com/palladidrago/mashovapi
description: Api for mashov.info. Log in, get your grades, without messing with http requests yourself.
version: 0.0.4

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  dio: ^3.0.10
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
